### ISSUE TITLE
Preparing to v4.1

### ISSUE THREAD

**Issue by dmitryvhf** [dmitryvhf/L2ScriptMaker#2]
After #1 must do simple refactoring.
> Simple - use only one-three simple modules for creation good solution architecture

- [x] Convert code to C# [ #1 ]
- [x] Split and move code for modules [ #6 ]
- [x] Add entity [ #8 ]
- [x] Add services [ #9 ]
- [x] Add unit and integration tests [ #10 ]

**Comment by dmitryvhf** [comment]
Preparation for full refactoring complete
